### ISSUE TITLE
Scheduler doesn't works with affinity

### ISSUE THREAD

**Issue by josericardomcastro** [tkestack/gpu-admission#15]
Hi! Can anyone help me with this?

When i use this scheduler-policy-config.json file:
```
{
  "kind": "Policy",
  "apiVersion": "v1",
  "predicates": [
    {
      "name": "PodFitsHostPorts"
    },
    {
      "name": "PodFitsResources"
    },
    {
      "name": "NoDiskConflict"
    },
    {
      "name": "MatchNodeSelector"
    },
    {
      "name": "HostName"
    }
  ],
  "extenders": [
    {
      "urlPrefix": "http://127.0.0.1:3456/scheduler",
      "apiVersion": "v1beta1",
      "filterVerb": "predicates",
      "enableHttps": false,
      "nodeCacheCapable": false
    }
  ],
  "hardPodAffinitySymmetricWeight": 10,
  "alwaysCheckAllPredicates": false
}
```

The scheduler doesn't use or respect my pod affinity rule:
```
affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: release
                  operator: In
                  values:
                  - appgpu
              topologyKey: kubernetes.io/hostname
            weight: 100
```

I don't want more the one replica pod in the same node.

Thanks!
