### ISSUE TITLE
does not support kubernetes 1.23

### ISSUE THREAD

**Issue by hwdef** [tkestack/gpu-admission#24]
https://kubernetes.io/docs/reference/scheduling/policies/

the `policy-config-file` is removed in kubernetes 1.23

**Comment by DennisYoung96** [comment]
yes, so how to make the KubeSchedulerConfiguration now? can anyone share that?(^_−)☆

**Comment by kevinfeng** [comment]
> 
I use config below and it works:
```
apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf
extenders:
- urlPrefix: "http://{ip}:{port}/scheduler"
  filterVerb: predicates
  enableHTTPS: false
  nodeCacheCapable: false
```

**Comment by jason-gideon** [comment]
1. gpu-admission need assgined to controlplane
2. perpare  scheduler-config.yaml as below
```
[root@loong64pc kube-scheduler-v1.25.5-KubeSchedulerConfiguration]# cat scheduler-config.yaml
apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: /etc/kubernetes/ssl/kubecfg-kube-scheduler.yaml
extenders:
- urlPrefix: "http://127.0.0.1:3456/scheduler"
  filterVerb: predicates
  enableHTTPS: false
  nodeCacheCapable: false
  ignorable: true
```
3. kube-scheduler --config scheduler-config.yaml
